<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>c664350d-b3b8-4366-817a-9ffb84b131d4</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Page Include="Program.cs" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Login.cs" />
    <Resource Include="SqliteAccess.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="BanHostDB.db">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.0.123" />
    <PackageReference Include="Microsoft.AspNetCore.Cors" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.HttpOverrides" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="6.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="6.0.0" />
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.116" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Clips\" />
    <Folder Include="ReceivedFiles\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="User.cs" />
    <Resource Include="web.config" />
  </ItemGroup>

  <ItemGroup>
    <None Update="mankey.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
